### ISSUE TITLE
add the missing "im_left"

### ISSUE THREAD

**Issue by JamesZhuh** [LouisFoucard/w-net#1]
Great work! I am trying testing and learning from your work.

It seems the origin go-through script missed the definition of "im_left".
I try to add the one-liner before the scripts need it and it seems to work:

im_left = stereo_im[:, np.r_[0, 0:img_cols-1],:] 

FYI.

**Comment by yyll008** [comment]
great!
Thanks, I meet this error, add your scripts on python3, solve it!

img_rows, img_cols = stereo_im.shape[0], stereo_im.shape[1]/2
im_left = stereo_im[:,np.r_[0,0:(int(img_cols)-1)],:]

**Comment by LouisFoucard** [comment]
Thx, this is now fixed
